DESC="DevOps: docker, helm, grafana, terraform, vault, consul, ansible, CLIs de k8s e nixpacks"
REPOS=(docker helm grafana hashicorp)
APT=(ansible ansible-lint terraform vault consul)
CONFIGS=(.config/lazydocker .config/k9s .config/k3d .config/helm .config/argocd .config/act)
POS=(pos_devops)
