DESC="Virtualizacao: qemu, libvirt, virt-manager, tigervnc, bridge-utils e vagrant"
APT=(bridge-utils libvirt-clients libvirt-daemon-system libvirt-dev qemu-system-x86 tigervnc-viewer virt-manager)
REPOS=(hashicorp)
